<?php

namespace labo\Bundle\TestmanuBundle\Entity;

use labo\Bundle\TestmanuBundle\Entity\baseRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * collectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class collectionRepository extends baseRepository {
	

	/**
	 * findDiapoBySlug
	 * Renvoie la collection et les images liées
	 * @param string $collSlug
	 * @return 
	 */
	public function findDiapoBySlug($collSlug) {
		$qb = $this->createQueryBuilder('element');
		$qb->where('element.slug = :slug')
			->setParameter('slug', $collSlug);
		$qb->leftJoin('element.medias', 'em')
			->addSelect('em');
		$qb = $this->genericFilter($qb);
		// $qb->orderBy('element.datedebut', 'DESC');
		return $qb->getQuery()->getResult();
	}


}
