<?php

namespace AcmeGroup\LaboBundle\Entity;

use AcmeGroup\LaboBundle\Entity\baseRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * ficheCreativeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ficheCreativeRepository extends baseRepository {

	/**
	* findActifs
	* Liste des éléments de statut = actif
	* @return array
	*/
	public function findAllFiches() {
		$qb = $this->createQueryBuilder('element');
		$qb->leftJoin('element.image', 'i')
			->addSelect('i')
			;
		$qb = $this->genericFilter($qb);
		$qb->orderBy('element.dateCreation', 'DESC');
		return $qb->getQuery()->getResult();
	}

	/**
	* getFicheBySlug
	* Renvoie une fiche selon slug
	* @return array
	*/
	public function getFicheBySlug($slug) {
		$qb = $this->createQueryBuilder('element');
		$qb->where('element.slug = :slug')
			->setParameter('slug', $slug)
			->leftJoin('element.image', 'i')
			->addSelect('i')
			;
		$qb = $this->genericFilter($qb);
		// $qb->orderBy('element.dateCreation', 'DESC');
		return $qb->getQuery()->getResult();
	}


}
