<?php

namespace AcmeGroup\LaboBundle\Entity;

use AcmeGroup\LaboBundle\Entity\baseRepository;

/**
 * pagewebRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pagewebRepository extends baseRepository {

	public function findWithRichtexts($slug) {
		$qb = $this->createQueryBuilder('element');
		$qb->where('element.slug = :slug')
			->setParameter('slug', $slug)
			->leftJoin('element.richtexts', 'r')
			;
		$r = $qb->getQuery()->getOneOrNullResult();
		return $r;
	}

}
