<?php

namespace labo\Bundle\TestmanuBundle\Entity;

use labo\Bundle\TestmanuBundle\Entity\baseRepository;

/**
 * panierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class panierRepository extends baseRepository {

	private $userId;

	public function setUser($user) {
		$this->userId = $user;
	}

	public function getUserArticles($userId) {
		$qb = $this->createQueryBuilder('element');
		$qb->leftJoin('element.propUser', 'user')
			->where('user.id = :u')
			->setParameter('u', $userId)
			// ->addSelect('user')
			->leftJoin('element.article', 'art')
			->addSelect('art');
		return $qb->getQuery()->getResult();
	}

	public function getUserPanier($userId) {
		$qb = $this->createQueryBuilder('element');
		$qb->leftJoin('element.propUser', 'user')
			->where('user.id = :u')
			->setParameter('u', $userId);
		return $qb->getQuery()->getResult();
	}

	public function getOneArticleOfUser($articleId, $userId) {
		$qb = $this->createQueryBuilder('element');
		$qb->where('element.propUser = :u')
			->setParameter('u', $userId)
			->andWhere('element.article = :art')
			->setParameter('art', $articleId);
		return $qb->getQuery()->getOneOrNullResult();
	}




}
