<?php

namespace labo\Bundle\TestmanuBundle\Entity;

use labo\Bundle\TestmanuBundle\Entity\laboBaseRepository;
use \Exception;

/**
 * panierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class panierRepository extends laboBaseRepository {

	private $userId;

	public function setUser($user) {
		$this->userId = $user;
	}

	public function getUserArticles($userId) {
		$qb = $this->createQueryBuilder('element');
		$qb->leftJoin('element.propUser', 'user')
			->where('user.id = :u')
			->setParameter('u', $userId)
			// ->addSelect('user')
			->leftJoin('element.article', 'art')
			->addSelect('art')
			// articles actifs only
			// ->join('art.statut', 'statut')
			// ->andWhere('statut.nom = :actif')
			// ->setParameter('actif', 'Actif')
			;
		$qb = $this->defaultStatut($qb);
		return $qb->getQuery()->getResult();
	}

	public function getUserPanier($userId) {
		$qb = $this->createQueryBuilder('element');
		$qb->leftJoin('element.propUser', 'user')
			->where('user.id = :u')
			->setParameter('u', $userId)
			// articles actifs only
			->join('element.article', 'art')
			// ->addSelect('art')
			->join('art.statut', 'statut')
			->andWhere('statut.nom = :actif')
			->setParameter('actif', 'Actif')
			;
		return $qb->getQuery()->getResult();
	}

	public function getOneArticleOfUser($articleId, $userId) {
		$qb = $this->createQueryBuilder('element');
		$qb->where('element.propUser = :u')
			->setParameter('u', $userId)
			->join('element.article', 'art')
			->andWhere('art.id = :id')
			->setParameter('id', $articleId)
			// articles actifs only
			// ->join('art.statut', 'statut')
			// ->andWhere('statut.nom = :actif')
			// ->setParameter('actif', 'Actif')
			;
		try {
			$r = $qb->getQuery()->getSingleResult();
		} catch (Exception $e) {
			$r = null;
		}
		return $r;
	}




}
