<?php

namespace labo\Bundle\TestmanuBundle\Entity;

use labo\Bundle\TestmanuBundle\Entity\laboBaseRepository;

/**
 * parametreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class parametreRepository extends laboBaseRepository {
	

	/**
	 * Recherche paramètres par groupes
	 * @param string/array $groups
	 */
	public function findByGroupeNom($groups) {
		if(is_string($groups)) $groups = array($groups);
	}

}
