<?php

namespace labo\Bundle\TestmanuBundle\Entity;

use labo\Bundle\TestmanuBundle\Entity\laboBaseRepository;

/**
 * richtextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class richtextRepository extends laboBaseRepository {


	/***************************************************************/
	/*** Méthodes conditionnelles
	/***************************************************************/

	/**
	* ofType
	* Sélect typeRichtext de version = $version uniquement
	*
	*/
	private function ofType(\Doctrine\ORM\QueryBuilder $qb, $typeRichtext = null) {
		if($typeRichtext !== null) {
			$qb->join('element.typeRichtexts', 'trt')
				->andWhere('trt.nom = :t')
				->setParameter('t', $typeRichtext);
		}
		return $qb;
	}


}
