<?php

namespace AcmeGroup\LaboBundle\Entity;

use AcmeGroup\LaboBundle\Entity\baseRepository;

/**
 * tauxTVARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tauxTVARepository extends baseRepository {

	/**
	* defaultVal
	* Renvoie l'instance de la version par défaut (ou null)
	*/
	public function defaultVal() {
		$qb = $this->createQueryBuilder('element')
			->where('element.nom = :n')
			->setParameter('n', "normal");
		return $qb->getQuery()->getResult();
	}


}
