<?php

namespace labo\Bundle\TestmanuBundle\Entity;

use labo\Bundle\TestmanuBundle\Entity\baseRepository;

/**
 * typeEvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class typeEvenementRepository extends baseRepository {

	/**
	* defaultVal
	* Renvoie les versions pour fixtures
	*/
	public function defaultVal() {
		$qb = $this->createQueryBuilder('element');
		$qb->where('element.id = :idval')
			->setParameter('idval', '2');
		return $qb->getQuery()->getResult();
	}


}
