<?php

namespace labo\Bundle\TestmanuBundle\Entity;

use labo\Bundle\TestmanuBundle\Entity\laboBaseRepository;

/**
 * typeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class typeRepository extends laboBaseRepository {

	/** Renvoie la(les) valeur(s) par défaut --> ATTENTION : dans un array()
	 * @param string/array $defaults = liste des éléments par défaut
	 */
	public function defaultVal($defaults = null) {
		if(is_string($defaults)) $defaults = array($defaults);
		$qb = $this->createQueryBuilder('element');
		if(is_array($defaults) && (count($defaults) > 0)) {
			// récupère les éléments listés
			$qb->where($qb->expr()->in('element.nom', $defaults));
		} else {
			// sinon uniquement le premier
			$qb->setMaxResults(1);
		}
		$qb->orderBy('element.id', 'ASC');
		return $qb->getQuery()->getResult();
	}

}
