<?php

namespace labo\Bundle\TestmanuBundle\Entity;

use labo\Bundle\TestmanuBundle\Entity\laboBaseRepository;

/**
 * typePartenaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class typePartenaireRepository extends laboBaseRepository {

	/** Renvoie la(les) valeur(s) par défaut --> ATTENTION : dans un array()
	* @param $defaults = liste des éléments par défaut
	*/
	public function defaultVal($defaults = null) {
		if(is_string($defaults)) $defaults = array($defaults);
		if(!is_array($defaults)) $defaults = null;
		$qb = $this->createQueryBuilder('element');
		if($defaults !== null) $qb->where($qb->expr()->in('element.nom', $defaults));
		return $qb->getQuery()->getResult();
	}

}
