<?php

namespace AcmeGroup\LaboBundle\Entity;

use AcmeGroup\LaboBundle\Entity\baseRepository;

/**
 * versionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class versionRepository extends baseRepository {

	/**
	* defaultVal
	* Renvoie les versions pour fixtures
	*/
	public function defaultVal() {
		$qb = $this->createQueryBuilder('element');
		// $qb->where('element.defaut = :true')
		// 	->setParameter('true', 1);
		return $qb->getQuery()->getResult();
	}

	/**
	* defaultVersion
	* Renvoie l'instance de la version par défaut (ou null)
	*/
	public function defaultVersion() {
		$qb = $this->createQueryBuilder('element');
		$qb->where('element.defaut = :true')
			->setParameter('true', 1);
		return $qb->getQuery()->getOneOrNullResult();
	}

}