<?php

namespace labo\Bundle\TestmanuBundle\Entity;

use labo\Bundle\TestmanuBundle\Entity\laboBaseRepository;

/**
 * versionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class versionRepository extends laboBaseRepository {

	public function __call($name, $arguments = null) {
		switch ($name) {
			case 'is'.ucfirst($this->getName()):
				$reponse = true;
				break;
			default:
				$reponse = false;
				break;
		}
		return $reponse;
	}

	public function getName() {
		return 'versionRepository';
	}

	/**
	* defaultVal
	* Renvoie les versions par défaut
	* @return version / null
	*/
	public function defaultVal() {
		return $this->defaultVersion();
	}

	/**
	* defaultVersion
	* Renvoie l'instance de la version par défaut (ou null)
	* @return version / null
	*/
	public function defaultVersion() {
		$qb = $this->createQueryBuilder('element');
		$qb->where('element.defaut = :true')
			->setParameter('true', 1)
			->setMaxResults(1);
		return $qb->getQuery()->getOneOrNullResult();
	}

	/**
	* defaultVersion
	* Renvoie l'instance de la version en cours (ou null)
	* @return version / null
	*/
	public function currentVersion() {
		$slug = "mettre ici la version par défaut";
		$qb = $this->createQueryBuilder('element');
		$qb->where('element.slug = :slug')
			->setParameter('slug', $slug);
		return $qb->getQuery()->getOneOrNullResult();
	}

}

