<?php

namespace AcmeGroup\LaboBundle\Entity;

use AcmeGroup\LaboBundle\Entity\baseRepository;

/**
 * videoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class videoRepository extends baseRepository {

	public function getVideos($recherche = null) {
		$qb = $this->createQueryBuilder('element');
		$qb = $this->excludeExpired($qb);
		$qb = $this->defaultStatut($qb);
		$qb = $this->withVersion($qb);
		$qb->orderBy('element.dateCreation', 'DESC');
		return $qb->getQuery()->getResult();
	}


}
