<?php

namespace labo\Bundle\TestmanuBundle\Entity;

use labo\Bundle\TestmanuBundle\Entity\baseRepository;

/**
 * villesFranceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class villesFranceRepository extends baseRepository {

	/**
	* defaultVal
	* Renvoie les versions pour fixtures
	*/
	public function defaultVal() {
		$qb = $this->createQueryBuilder('element');
		$qb->where('element.nom like :pays')
			->setParameter('pays', "France");
		return $qb->getQuery()->getResult();
	}

}
